// Feel free to edit this file, it won't be regenerated by gir generator unless removed.

#include <libsecret/secret.h>

//Fake enum Error.invalid_file_format as Github CI don't have it
#ifndef SECRET_ERROR_INVALID_FILE_FORMAT
#define SECRET_ERROR_INVALID_FILE_FORMAT 5
#endif
