#![cfg_attr(feature = "cargo-clippy", allow(match_same_arms))]
#![cfg_attr(feature = "cargo-clippy", allow(let_and_return))]

extern crate case;
extern crate docopt;
extern crate env_logger;
#[macro_use]
extern crate error_chain;
extern crate git2;
#[macro_use]
extern crate lazy_static;
#[macro_use]
extern crate log;
extern crate xml;
extern crate toml;
extern crate regex;
extern crate time;
extern crate hprof;
extern crate stripper_lib;

use std::cell::RefCell;

use env::Env;
use library::Library;
use hprof::Profiler;

//generated by build.rs
mod gir_version;

mod analysis;
mod chunk;
mod codegen;
mod config;
mod consts;
mod env;
mod file_saver;
mod git;
mod library;
mod library_postprocessing;
mod nameutil;
mod parser;
mod traits;
mod version;
mod writer;

use self::config::error::*;

#[cfg_attr(test, allow(dead_code))]
fn main() {
    if let Err(ref e) = do_main() {
        println!("{}", e);

        for e in e.iter().skip(1) {
            println!("caused by: {}", e);
        }

        ::std::process::exit(1);
    }
}

fn do_main() -> Result<()> {
    if std::env::var_os("RUST_LOG").is_none() {
        std::env::set_var("RUST_LOG", "gir=warn");
    }
    try!(env_logger::init());

    let mut cfg = match config::Config::new() {
        Ok(cfg) => cfg,
        Err(Error(ErrorKind::CommandLine(ref err), _)) => {
            // Fatal errors processed in same branch
            // to prevent repeat message in "caused by:"
            if err.fatal() {
                println!("error: {}", err);
            } else {
                println!("{}", err);
            }
            return Ok(());
        }
        Err(err) => return Err(err),
    };

    let statistics = Profiler::new("Gir");
    statistics.start_frame();

    let watcher_total = statistics.enter("Total");
    let watcher_loading = statistics.enter("Loading");

    let mut library = Library::new(&cfg.library_name);
    try!(library.read_file(&cfg.girs_dir, &cfg.library_full_name()));
    library.postprocessing();

    cfg.resolve_type_ids(&library);
    let namespaces = analysis::namespaces::run(&library);
    let symbols = analysis::symbols::run(&library, &namespaces);
    let class_hierarchy = analysis::class_hierarchy::run(&library);

    let mut env = Env {
        library: library,
        config: cfg,
        namespaces: namespaces,
        symbols: RefCell::new(symbols),
        class_hierarchy: class_hierarchy,
        analysis: Default::default(),
    };

    drop(watcher_loading);
    {
        let _watcher = statistics.enter("Analysing");
        analysis::run(&mut env);
    }

    {
        let _watcher_generating = statistics.enter("Generating");

        codegen::generate(&env);
    }

    drop(watcher_total);
    statistics.end_frame();

    if env.config.show_statistics {
        statistics.print_timing();
    }

    Ok(())
}
